version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging into ECR


  build:
    commands:
      - docker build -t mytestproject:latest -f Dockerfile .
      - docker tag mytestproject:latest mytestproject:latest


  post_build:
    commands:
      - docker push satee143/mytestproject:latest
