version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - docker build -t t mypublicdocker:${image_tag} -f Dockerfile .
      
  post_build:
    commands:
      - docker push public.ecr.aws/e5r7r1t8/mypublicdocker:${image_tag}
