version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install pytest
      - pip3 install webdriver-manager
      - pip3 install selenium 
      - pip3 install pytest-html 
  build:
    commands:
      - python -m pytest --html=pytest_reports/pytest_report.html --self-contained-html
      
  post_build:
    commands:
      - aws s3 cp ./pytest_reports/pytest_report.html s3://mytestbucketfortrigger/pytest_report.html 
      - |
        echo "HTML Report:https://s3.console.aws.amazon.com/s3/object/mytestbucketfortrigger?region=us-east-1&prefix=pytest_report.html"   

reports:
  pytest_reports:
    files:
      - pytest_report.html
    base-directory: pytest_reports/
    file-format: HTML
