version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging into ECR


  build:
    commands:
      - docker build -t mydockerfirst -f Dockerfile .
      - docker tag mydockerfirst:latest 118400959103.dkr.ecr.us-east-1.amazonaws.com/mydockerfirst:latest
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 674715443267.dkr.ecr.us-east-1.amazonaws.com


  post_build:
    commands:
      - docker push 118400959103.dkr.ecr.us-east-1.amazonaws.com/mydockerfirst:latest
