version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging into ECR

  build:
    commands:
      - docker build -t mypublicdocker:${image_tag} -f Dockerfile .
      - docker tag mydockerfirst:latest 118400959103.dkr.ecr.us-east-1.amazonaws.com/mydockerfirst:latest
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/e5r7r1t8

      
  post_build:
    commands:
      - docker push 118400959103.dkr.ecr.us-east-1.amazonaws.com/mydockerfirst:latest
