version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging into ECR
      - eval $(aws ecr get-login --no-include-email --region us-east-1

  build:
    commands:
      - docker build -t mydockerfirst -f Dockerfile .
      - docker tag mydockerfirst:latest 118400959103.dkr.ecr.us-east-1.amazonaws.com/mydockerfirst:latest


  post_build:
    commands:
      - docker push 118400959103.dkr.ecr.us-east-1.amazonaws.com/mydockerfirst:latest
